**Merging GDP with the existing Dataset**

In [1]:
import pandas as pd
import numpy as np

In [55]:
og_df = pd.read_csv('Air Traffic New.csv')
og_df.head()

,Date,domestic passengers,international passenegrs,domestic freight(in tonne),international freight(in tonne)
0,01-01-2009,3288004,885435,20832,11675
1,01-02-2009,3293220,757168,18645,12482
2,01-03-2009,3122400,848046,23046,15359
3,01-04-2009,3266686,861715,21623,14512
4,01-05-2009,3883887,898410,19534,14586

In [56]:
og_df.set_index('Date')

,domestic passengers,international passenegrs,domestic freight(in tonne),international freight(in tonne)
Date,,,,
01-01-2009,3288004,885435,20832,11675
01-02-2009,3293220,757168,18645,12482
01-03-2009,3122400,848046,23046,15359
01-04-2009,3266686,861715,21623,14512
01-05-2009,3883887,898410,19534,14586
...,...,...,...,...
01-02-2025,14118495,2862912,58353,24317
01-03-2025,14541682,2907654,68421,28473
01-04-2025,14314688,3007716,65982,22465
01-05-2025,14054824,2974203,71524,29588
01-06-2025,13604312,2754143,78227,34822

In [57]:
new_df = pd.read_csv('gdp.csv')
new_df.head()

         Date          GDP
0  01-01-2009  1432646.640
1  01-02-2009  1432646.640
2  01-03-2009  1432646.640
3  01-04-2009  1497644.892
4  01-05-2009  1497644.892

In [58]:
combined_data = pd.merge(og_df,new_df,on='Date')
combined_data

,Date,domestic passengers,international passenegrs,domestic freight(in tonne),international freight(in tonne),GDP
0,01-01-2009,3288004,885435,20832,11675,1.432647e+06
1,01-02-2009,3293220,757168,18645,12482,1.432647e+06
2,01-03-2009,3122400,848046,23046,15359,1.432647e+06
3,01-04-2009,3266686,861715,21623,14512,1.497645e+06
4,01-05-2009,3883887,898410,19534,14586,1.497645e+06
...,...,...,...,...,...,...
187,01-08-2024,13130699,2779337,67297,24436,4.493587e+07
188,01-09-2024,13027336,2671124,67253,26496,4.493587e+07
189,01-10-2024,13657193,2765194,71177,22335,4.726542e+07
190,01-11-2024,14250266,2812305,60450,23651,4.726542e+07
191,01-12-2024,14926352,3051909,67166,27067,4.726542e+07

In [59]:
combined_data.to_csv('new_data.csv',index=False)